
# Admittance parameters for PowerPassFilter
mass: [  2,  0,  0,  0,  0,  0,
         0,  2,  0,  0,  0,  0,
         0,  0,  2,  0,  0,  0,
         0,  0,  0,  1,  0,  0,
         0,  0,  0,  0,  1,  0,
         0,  0,  0,  0,  0,  1]

damping: [  2,  0,  0,  0,  0,  0,
            0,  2,  0,  0,  0,  0,
            0,  0,  2,  0,  0,  0,
            0,  0,  0,  2,  0,  0,
            0,  0,  0,  0,  2,  0,
            0,  0,  0,  0,  0,  2]


ft_sensor_rotation: [-1 , 0 , 0,
                      0 , 1 , 0,
                      0 , 0 , -1]